name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false  # Prevents cancellation of other jobs if one fails
      matrix:
        include:
          - python-version: 3.5
            python-arch: x86
            tox-env: py35
            tox-args: ""
          - python-version: 3.5
            python-arch: x64
            tox-env: py35
            tox-args: "tornado.test.websocket_test"
          - python-version: 3.6
            python-arch: x86
            tox-env: py36
            tox-args: "tornado.test.websocket_test"
          - python-version: 3.6
            python-arch: x64
            tox-env: py36
            tox-args: ""
          - python-version: 3.7
            python-arch: x86
            tox-env: py37
            tox-args: "tornado.test.websocket_test"
          - python-version: 3.7
            python-arch: x64
            tox-env: py37
            tox-args: ""

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }} (${{ matrix.python-arch }})
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}

      - name: Install dependencies
        run: |
          python -m pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' --user --upgrade pip
          python -m pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' tox wheel

      - name: Run tests
        run: tox -e ${{ matrix.tox-env }} -- ${{ matrix.tox-args }}

      - name: Build wheels
        if: success()
        run: python setup.py bdist_wheel

      - name: List built wheels
        run: ls dist

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl
