name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2018
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.5
            architecture: x86
            tox-env: py35
            tox-args: ""
          - python-version: 3.5
            architecture: x64
            tox-env: py35
            tox-args: "tornado.test.websocket_test"
          - python-version: 3.6
            architecture: x86
            tox-env: py36
            tox-args: "tornado.test.websocket_test"
          - python-version: 3.6
            architecture: x64
            tox-env: py36
            tox-args: ""
          - python-version: 3.7
            architecture: x86
            tox-env: py37
            tox-args: "tornado.test.websocket_test"
          - python-version: 3.7
            architecture: x64
            tox-env: py37
            tox-args: ""
    env:
      TORNADO_EXTENSION: "1"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Python build tools and dependencies
        run: |
          echo "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64" >> $GITHUB_PATH
          python -m pip --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' install --upgrade pip
          pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' setuptools wheel tox

      - name: Add Python to PATH
        run: echo "${{ env.pythonLocation }}" >> $GITHUB_PATH

      - name: Run tests and build wheels
        run: |
          tox -e ${{ matrix.tox-env }} -- ${{ matrix.tox-args }}
          if ($LASTEXITCODE -eq 0) { python setup.py bdist_wheel }

      - name: List built wheels
        run: dir dist

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl
